### ISSUE TITLE
if you have tested the changes in the use of VRAM for graphics card rendering before and after compression?

### ISSUE THREAD

**Issue by smart4654154** [Xiangyu1Sun/Factorize-3DGS#1]
Thank you very much for your work
The data compression work is excellent
May I ask if you have tested the changes in the use of VRAM for graphics card rendering before and after compression?
What I mean is to use specific data testing to obtain changes in the usage of VRAM
May I ask if you have specific test results?I want to know the specific changes.thank you

**Comment by Xiangyu1Sun** [comment]
We evaluate the VRAM required for both training and inference of our factorized 3DGS approach on the synthetic-NeRF dataset.

![1727086726285](https://github.com/user-attachments/assets/dffc8dae-4f54-4e14-9720-f3b48782a4e6)
